declare module 'lucide-react' {
  import type { FC, SVGProps } from 'react'
  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number | string
  }
  export type Icon = FC<LucideProps>
  export type LucideIcon = Icon
  export const Activity: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const ArrowDownLeft: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUpRight: Icon
  export const Award: Icon
  export const Ban: Icon
  export const BarChart3: Icon
  export const Bell: Icon
  export const BellRing: Icon
  export const Binary: Icon
  export const BookOpen: Icon
  export const Bookmark: Icon
  export const Building: Icon
  export const Building2: Icon
  export const Calendar: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronUp: Icon
  export const ClipboardList: Icon
  export const Clock: Icon
  export const Code: Icon
  export const Copy: Icon
  export const CreditCard: Icon
  export const Crown: Icon
  export const DollarSign: Icon
  export const Download: Icon
  export const Edit3: Icon
  export const ExternalLink: Icon
  export const ExternalLinkIcon: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const FileText: Icon
  export const Filter: Icon
  export const Flag: Icon
  export const Gift: Icon
  export const Github: Icon
  export const Globe: Icon
  export const GraduationCap: Icon
  export const Grid: Icon
  export const Hash: Icon
  export const Heart: Icon
  export const HelpCircle: Icon
  export const Info: Icon
  export const Layers: Icon
  export const Link: Icon
  export const Linkedin: Icon
  export const List: Icon
  export const Loader2: Icon
  export const Lock: Icon
  export const LogOut: Icon
  export const LucideIcon: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Medal: Icon
  export const Menu: Icon
  export const MessageSquare: Icon
  export const Minus: Icon
  export const Moon: Icon
  export const MoreHorizontal: Icon
  export const Package: Icon
  export const Percent: Icon
  export const Phone: Icon
  export const PieChart: Icon
  export const Plus: Icon
  export const RefreshCw: Icon
  export const Rocket: Icon
  export const RotateCw: Icon
  export const Search: Icon
  export const Send: Icon
  export const Settings: Icon
  export const Share2: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const SlidersHorizontal: Icon
  export const SortAsc: Icon
  export const SortDesc: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Store: Icon
  export const Sun: Icon
  export const Tag: Icon
  export const Target: Icon
  export const Terminal: Icon
  export const ThumbsDown: Icon
  export const ThumbsUp: Icon
  export const Trash2: Icon
  export const TrendingDown: Icon
  export const TrendingUp: Icon
  export const Twitter: Icon
  export const Unlock: Icon
  export const Upload: Icon
  export const User: Icon
  export const UserCheck: Icon
  export const Users: Icon
  export const Wallet: Icon
  export const X: Icon
  export const XCircle: Icon
  export const Zap: Icon
}
